#!/bin/sh
#
cd $(dirname $0); top=$(pwd); cd config

wait_for_up=${1:-30} # set up the time before the ./lists script is run

os=$(uname)
case $os in
  Linux)
    IP_LOOKUP="$(ip route get 8.8.8.8 | awk '{for(i=1;i<=NF;i++) if ($i=="src") print $(i+1)}')"  # May not work for VPN / tun0
    IPv6_LOOKUP="$(ip -6 route get 2001:4860:4860::8888 | awk '{for(i=1;i<=NF;i++) if ($i=="src") print $(i+1)}')"  # May not work for VPN / tun0
    ;;
  Darwin)
    interface=$(route get 8.8.8.8 | grep interface | awk '{print $2}')
    IP_LOOKUP=$(ifconfig $interface | grep 'inet ' | awk '{print $2}')
    IPv6_LOOKUP=$(ifconfig $interface | grep 'inet6 ' |
      awk '{print $2}' | sed 's/%.*//')
    ;;
esac

IP="${IP:-$IP_LOOKUP}"  # use $IP, if set, otherwise IP_LOOKUP
IPv6="${IPv6:-$IPv6_LOOKUP}"  # use $IPv6, if set, otherwise IP_LOOKUP
DOCKER_CONFIGS="$(pwd)"  # Default of directory you run this from, update to where ever.

echo "### Make sure your IPs are correct, hard code ServerIP ENV VARs if necessary\nIP: ${IP}\nIPv6: ${IPv6}"

# If PIHOLE_DNS environment is not set, use these defaults:
#
if [ -z "$PIHOLE_DNS" ]; then PIHOLE_DNS="9.9.9.9"; fi

D_DNS="--dns 127.0.0.1"
for i in $PIHOLE_DNS
do
  D_DNS="$D_DNS --dns $i"
done

# Uncomment this to get DHCP in pihole
# DHCP="-p 67:67/udp"

docker run -d \
    --name pihole \
    -p 53:53/tcp -p 53:53/udp \
    $DHCP \
    -p 80:80 \
    -p 443:443 \
    -v "${DOCKER_CONFIGS}/pihole/:/etc/pihole/" \
    -v "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/dnsmasq.d/" \
    -v $top/lists:/tmp/run_config \
    -e ServerIP="${IP}" \
    -e ServerIPv6="${IPv6}" \
    --restart=unless-stopped \
    --cap-add=NET_ADMIN \
    $D_DNS \
    pihole/pihole:latest

# echo -n "Your password for https://${IP}/admin/ is "
# docker logs pihole 2> /dev/null | grep 'password'
sleep $wait_for_up
docker exec -i pihole /tmp/run_config
